### ISSUE TITLE
Der Quelltext ist nicht ausreichend Deutsch!

### ISSUE THREAD

**Issue by piotrwyrw** [piotrwyrw/flatterig-vogel#1]
Die Wörter "Responsive Design" und "Falling edge" sollten SOFORT in die Volkssprache übersetzt werden!

**Comment by ShortyPing** [comment]
Das finde ich SEHR gut

**Comment by piotrwyrw** [comment]
Die Käfer wurden im Begehen c5c014d54adbf1b98bb5688e9c431b28505c2db0 eliminiert!
